import os


DATABASE_URL = os.environ['DATABASE_URL']
BEER_CLIENT_HOST = os.environ['BEER_CLIENT_HOST']

WS_URL = "/beersocket"

MIN_ML_CANA = 200
MAX_ML_CANA = 300
MIN_ML_DOBLE = 500
MAX_ML_DOBLE = 500
MIN_ML_JARRA = 800
MAX_ML_JARRA = 1000
